package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	. "plaso2graph/master/src/Entity"
	. "plaso2graph/master/src/Extractor"
	"strings"
	"time"
)

var (
	source         = flag.String("source", "data/output.json", "Source CSV File generated by plaso")
	output_dir     = flag.String("output", "output/output.json", "Output Json File")
	extractor_name = flag.String("extractor", "neo4j", "Type of Extractor to use. (default: neo4j, maltego)")
)

func HandleErr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func compare(a string, b string) bool {
	return strings.Compare(a, b) == 0
}

func ValidateArgs() {
	// Check if source exists
	if _, err := os.Stat(*source); err != nil {
		fmt.Printf("Source file \"%s\" Does not exist\n", *source)
		log.Fatal()
	}

	if _, err := os.Stat(*output_dir); err == nil {
		fmt.Printf("Output file \"%s\" already exists exist\n", *output_dir)
	}

	if compare(*extractor_name, "neo4j") && compare(*extractor_name, "maltego") {
		fmt.Println("Extractor must be one from: neo4j, maltego.")
		fmt.Println("Extractor: ", *extractor_name)
	}
}

func containsString(strings []string, str string) bool {
	for _, s := range strings {
		if s == str {
			return true
		}
	}
	return false
}

func enumEventData(data []PlasoLog) []string {
	var res []string

	for _, d := range data {
		if d.EvtxLog != nil {
			for _, dataName := range d.EvtxLog.EventData.Data {
				if !containsString(res, dataName.Name) {
					res = append(res, dataName.Name)
				}
			}
		}
	}
	return res
}

func enumPlaso(data []PlasoLog) []string {
	var res []string
	for _, d := range data {
		if !containsString(res, d.DataType) {
			res = append(res, d.DataType)
		}
	}
	return res
}

func main() {
	flag.Parse()
	ValidateArgs()
	t := time.Now()

	// Parse Plaso File
	ps, users, computers, domains, tasks, webhistories := ParseFile(*source)
	elapsed := time.Since(t)

	//Aggregate data from Plaso
	log.Printf("Read and Aggregated Data in : %s \n", elapsed)

	fmt.Printf("Process : %d\n", len(ps))
	fmt.Printf("User : %d\n", len(users))
	fmt.Printf("Computer : %d\n", len(computers))
	fmt.Printf("Domain : %d\n", len(domains))
	fmt.Printf("Task : %d\n", len(tasks))
	fmt.Printf("WebHistory : %d\n", len(webhistories))

	//Insert into Neo4j
	con := Neo4jConnect("admin", "admin", "bolt://localhost:7687")
	InsertProcesses(con, ps)
	InsertComputers(con, computers)
	InsertUsers(con, users)
	InsertScheduledTasks(con, tasks)
	InsertDomains(con, domains)
	Links(con)

}
