package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	. "plaso2graph/master/src"
	. "plaso2graph/master/src/Entity"
	. "plaso2graph/master/src/Extractor"
	"strings"
	"time"
)

var (
	source         = flag.String("source", "data/evtx_all.json", "Source CSV File generated by plaso")
	output_dir     = flag.String("output", "output/output.json", "Output Json File")
	extractor_name = flag.String("extractor", "neo4j", "Type of Extractor to use. (default: neo4j, maltego)")
)

func HandleErr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func compare(a string, b string) bool {
	return strings.Compare(a, b) == 0
}

func ValidateArgs() {
	// Check if source exists
	if _, err := os.Stat(*source); err != nil {
		fmt.Printf("Source file \"%s\" Does not exist\n", *source)
		log.Fatal()
	}

	if _, err := os.Stat(*output_dir); err == nil {
		fmt.Printf("Output file \"%s\" already exists exist\n", *output_dir)
	}

	if compare(*extractor_name, "neo4j") && compare(*extractor_name, "maltego") {
		fmt.Println("Extractor must be one from: neo4j, maltego.")
		fmt.Println("Extractor: ", *extractor_name)
	}
}

func main() {
	flag.Parse()
	ValidateArgs()
	t := time.Now()
	dat := ParseFile(*source)
	elapsed := time.Since(t)
	log.Printf("Elapsed Time: %s", elapsed)
	size := len(dat)
	fmt.Printf("Line parsed : %d \n", size)

	processes := GetProcesses(dat)

	con := Neo4jConnect("admin", "admin", "bolt://localhost:7687")
	InsertProcesses(con, processes)

}
